server:
  port: 18182


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: gzm2001..
  security:
    user:
      name: admin
      password: 123456


  mybatis:
    mapper-locations: classpath:com/strong/mapper/*.xml
    type-aliases-package: com.strong.entity